# Generated by Django 5.0.6 on 2024-06-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzusers',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
