# Generated by Django 5.0.6 on 2024-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzusers',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
