# Generated by Django 5.0.6 on 2024-06-20 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzmessages',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
