# Generated by Django 5.0.1 on 2024-06-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zzusers',
            name='profile_media',
            field=models.FileField(blank=True, null=True, upload_to='profile_media/'),
        ),
    ]
