# Generated by Django 5.0.6 on 2024-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0003_alter_zzusers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzusers',
            name='birthday',
            field=models.DateField(auto_now_add=True),
        ),
    ]
