# Generated by Django 5.0.6 on 2024-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0004_alter_zzusers_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzusers',
            name='latitude',
            field=models.FloatField(default=2.981),
        ),
        migrations.AlterField(
            model_name='zzusers',
            name='longitude',
            field=models.FloatField(default=6.321),
        ),
    ]
