# Generated by Django 5.0.1 on 2024-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0007_zzusers_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzusers',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
